version: '2'
services:
  #  db:
  #    image: mysql
  #    restart: always
  #    environment:
  #      MYSQL_ROOT_PASSWORD: dqx930215115
  #      MYSQL_DATABASE: ef
  #      MYSQL_USER: ef
  #      MYSQL_PASSWORD: dqx930215115

   web:
     build: .
    #  depends_on:
    #    - db
    #  links:
    #    - db
     ports:
       - "80:5000"
     restart: always
     environment:
       ASPNETCORE_ENVIRONMENT: Production