version: '2'
services:
  web:
    build: .
    #  depends_on:
    #    - db
    #  links:
    #    - db
    ports:
      - "80:5000"
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production